version: "2"
services:
  bridge:
    build:          .
    container_name: bridge
    command:        ./kandalf -c /config/config.yml -p /config/pipes.yml
    volumes:
      - "./build/out/linux:/app"
      - "./build/resources:/config"
    links:
      - logstash
      - kafka
      - redis
      - rmq

  elasticsearch:
    image:          elasticsearch:latest
    ports:
      - 9200:9200

  kafka:
    image:          spotify/kafka
    environment:
      TOPICS:       "customer_subscription,customer_created,default"

  kibana:
    image:          kibana:latest
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch

  logstash:
    image:          logstash:latest
    command:        logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    volumes:
      - "./build/resources/data/logstash/:/etc/logstash/conf.d/"
    links:
      - elasticsearch

  redis:
    image:          redis

  rmq:
    image:          rabbitmq:3-management
    volumes:
      - "./build/resources/data/rmq/:/etc/rabbitmq/"
    ports:
      - "5672:5672"
      - "15672:15672"
