# DO NOT USE IN PRODUCTION. THIS FILE IS ONLY FOR TESTING PURPOSES.
version:            "2"
services:
  kandalf_0:
    build:          .
    networks:
      default:
        ipv4_address: 172.16.238.10
    volumes:
      - "./build/out/linux:/app"
      - "./build/resources/kandalf:/config"
    links:
      - kafka
      - redis
      - rmq

  kandalf_1:
    build:          .
    networks:
      default:
        ipv4_address: 172.16.238.11
    volumes:
      - "./build/out/linux:/app"
      - "./build/resources/kandalf:/config"
    links:
      - kafka
      - redis
      - rmq

  kandalf_2:
    build:          .
    networks:
      default:
        ipv4_address: 172.16.238.12
    volumes:
      - "./build/out/linux:/app"
      - "./build/resources/kandalf:/config"
    links:
      - kafka
      - redis
      - rmq

  kafka:
    image:          spotify/kafka
    ports:
      - "9092:9092"
    environment:
      TOPICS:       "customer_subscription,customer_created,default"

  redis:
    image:          redis
    ports:
      - "6379:6379"

  rmq:
    image:          rabbitmq:3-management
    volumes:
      - "./build/resources/rmq:/etc/rabbitmq/"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER:  user
      RABBITMQ_DEFAULT_PASS:  password

# To hardcode ip addresses of kandalf containers
networks:
  default:
    driver:       bridge
    ipam:
      driver:     default
      config:
      - subnet:   172.16.238.0/24
        gateway:  172.16.238.1
