---
platform:       linux

image_resource:
  type:         docker-image
  source:
    repository: golang
    tag:        "1.7"

run:
  path:         app-master/ci/scripts/build-linux.sh

outputs:
  - name:       build

inputs:
  - name:       app-master
  - name:       semantic-version
