---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/hellofresh/ci-ansible

inputs:
  - name: source-code
  - name: automation-source-code
  - name: release-candidate

run:
  path: source-code/ci/scripts/deploy.sh
